### ISSUE TITLE
No redscript found error when enabling mod

### ISSUE THREAD

**Issue by sasoriza** [E1337Kat/cyberpunk2077_ext_redux#116] opened 2022-04-03 09:45 UTC
I am getting the following error when trying to install Limited HUD Improved Minimap Zoom Patch 2.12

Error: No Redscript found, should never get here.
    at Object.installRedscriptMod [as install] (C:\Users\xyz\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Cyberpunk 2077 Vortex Support v0.3.0\index.js:1416:31)
    at C:\Users\xyz\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Cyberpunk 2077 Vortex Support v0.3.0\index.js:1918:22
    at Object.install (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9163:35)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4070:11
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 

Windows 7 x64
Limited HUD Improved Minimap Zoom Patch 2.12
redscript 0.5.1
Cyberpunk 2077 Vortex Support 0.3.0
Vortex 1.5.7

**Comment by Bladehawke** [comment] 2022-04-03 09:52
Duplicate of #111 ?

**Comment by Bladehawke** [comment] 2022-04-03 09:55
As a workaround (not a fix), you can right click the mod and select "Unpack As-Is"

**Comment by Bladehawke** [comment] 2022-04-03 17:40
It looks (in my testing) like this is appropriately handled by #102.  We should have a test in there to make sure it doesn't regress.

**Comment by effs** [comment] 2022-04-07 11:03
This is fixed in #103, so 0.4.0. Should be out maybe today anyway, but @sasoriza in the meanwhile, you can use https://github.com/E1337Kat/cyberpunk2077_ext_redux/releases/tag/v0.4.0-preem

**Closed by effs** 2022-04-07 11:03 UTC
Labels: defect, Mod
